"""
pure_pursuit.py - Pure Pursuit Path Follower for QCar2
======================================================
Implements a geometrically-based trajectory tracking controller.
Calculates the Ackermann steering angle to chase a lookahead point
on a target global path generated by the SDCSRoadMap.
"""

import numpy as np
import math

class PurePursuitController:
    """
    Pure Pursuit Controller with inherent speed control.
    """
    def __init__(self, config):
        """
        Args:
            config: AppConfig containing pure_pursuit parameters.
        """
        self.cfg = config.pure_pursuit
        self.path = None
        self.last_closest_idx = 0
        self._prev_steering = 0.0  # For EMA smoothing

    def set_path(self, path):
        """
        Sets the global path to follow.
        
        Args:
            path: np.ndarray of shape (2, N) containing [x, y] coordinates.
        """
        self.path = path
        self.last_closest_idx = 0

    def get_closest_point_index(self, pose):
        """
        Finds the index of the closest path point to the current pose.
        Uses last_closest_idx to optimize search and prevent jumping backwards.
        """
        if self.path is None:
            return 0
            
        x, y = pose[0], pose[1]
        
        # Search forward from the last known closest point
        search_range = min(self.last_closest_idx + 200, self.path.shape[1])
        
        min_dist_sq = float('inf')
        closest_idx = self.last_closest_idx
        
        for i in range(self.last_closest_idx, search_range):
            px, py = self.path[0, i], self.path[1, i]
            dist_sq = (px - x)**2 + (py - y)**2
            
            if dist_sq < min_dist_sq:
                min_dist_sq = dist_sq
                closest_idx = i
                
        self.last_closest_idx = closest_idx
        return closest_idx

    def get_lookahead_point(self, pose):
        """
        Finds the lookahead point on the path.
        """
        if self.path is None:
            return None, None

        closest_idx = self.get_closest_point_index(pose)
        lookahead_distance_sq = self.cfg.lookahead_distance ** 2
        
        x, y = pose[0], pose[1]
        
        # Search forward along the path for the lookahead point
        for i in range(closest_idx, self.path.shape[1]):
            px, py = self.path[0, i], self.path[1, i]
            dist_sq = (px - x)**2 + (py - y)**2
            
            if dist_sq >= lookahead_distance_sq:
                return (px, py), i
                
        # If we reached the end of the path and didn't find a point far enough,
        # just return the last point on the path.
        last_idx = self.path.shape[1] - 1
        return (self.path[0, last_idx], self.path[1, last_idx]), last_idx

    def compute(self, pose):
        """
        Computes the steering angle and speed based on the current pose.
        
        Args:
            pose: tuple/list [x, y, theta] representing current state.
            
        Returns:
            tuple: (steering_angle_rad, target_velocity_m_s, lookahead_point)
        """
        if self.path is None:
            return 0.0, 0.0, None

        x, y, theta = pose
        lookahead_pt, target_idx = self.get_lookahead_point(pose)
        
        if lookahead_pt is None:
            return 0.0, 0.0, None

        lx, ly = lookahead_pt
        
        # Transform the lookahead point into the car's local coordinate frame
        # Car's origin is at the rear axle. X points forward, Y points left (standard ROS convention)
        dx = lx - x
        dy = ly - y
        
        local_x = math.cos(theta) * dx + math.sin(theta) * dy
        local_y = -math.sin(theta) * dx + math.cos(theta) * dy
        
        # If the lookahead point is physically behind the rear axle (local_x <= 0), 
        # it means we've overshot slightly. Steer hard towards it instead of giving up!
        if local_x <= 0:
             steer_dir = 1.0 if local_y > 0 else -1.0
             return steer_dir * 0.6, self.cfg.min_velocity, lookahead_pt
             
        # Pure Pursuit geometry: curvature = 2 * y / Ld^2
        # where Ld is the actual distance to the lookahead point.
        ld_sq = local_x**2 + local_y**2
        curvature = 2.0 * local_y / ld_sq
        
        # Ackermann steering angle = atan(curvature * wheelbase)
        raw_steering = math.atan(curvature * self.cfg.wheelbase)
        
        # Rate limiting: prevent wild steering jumps between steps
        max_rate = self.cfg.max_steering_rate
        delta = raw_steering - self._prev_steering
        if abs(delta) > max_rate:
            raw_steering = self._prev_steering + max_rate * (1 if delta > 0 else -1)
        
        # EMA smoothing: prevents jittery oscillations
        alpha = self.cfg.steering_alpha
        steering_angle = alpha * raw_steering + (1 - alpha) * self._prev_steering
        self._prev_steering = steering_angle
        
        # Curvature-based speed control: Slow down when the steering angle is high.
        # This keeps the car stable in sharp turns.
        speed_reduction = self.cfg.curve_slowdown_factor * abs(steering_angle)
        target_velocity = self.cfg.base_velocity - speed_reduction
        
        # Clamp velocity to minimum limit
        target_velocity = max(target_velocity, self.cfg.min_velocity)
        
        return steering_angle, target_velocity, lookahead_pt
